config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
  get '/new_user', to: 'users_controller#new_user', as: 'new_user'
  post '/new_user' , to: 'users_controller#new_user'
  get '/users/:id', to: 'users_controller#aff_profile_user'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true, uniqueness: true, length: {in: 3..10}
  validates :bio, presence: true, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
def initialize
  @errors = []
end

  def new_user
    if params['username'] != nil

      @a = params['username']
      @b = params['bio']

      @user = User.create(username: @a, bio: @b)
      # puts @user.id
      respond_to do |format|
        if @user.errors.any?
          @errors = @user.errors
          format.html { render :new_user }
        else
          format.html { redirect_to "/users/" + @user.id.to_s }
        end
      end
    end
  end

  def aff_profile_user
    if params[:id].to_i.to_s == params[:id]
      @ids = User.find(params[:id])
    else
      @ids = User.find_by(username: params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <title>Formulaire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>"Bienvenue sur ma page d'accueil ⛵️🎓😇" </h1>
<p> Pour créer un utilisateur, cliquez <%= link_to "ici", new_user_path %> </p>

app/views/users_controller/aff_profile_user.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
</head>
  <body>

      <p>Voici le numéro du gossip :</p>
     <p> <%= @ids.id %></p>
      <p>Voici l'auteur du gossip :</p>
      <p> <%= @ids.username%></p>
      <p> Voici le contenu du gossip :</p>
<p> <%= @ids.bio %></p>  </body>
</html>

app/views/users_controller/new_user.html.erb
<h1>Bienvenue dans la création d'utilisateurs !</h1>
<% if @errors.any? %>
L'utilisateur n'a pas été créé car :
<ul>
<% @errors.messages.each do |error| %>
  <li><%= error[0] %></li>
  <ul>
  <% error[1].each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
</ul>

<% end %>
<form action="/new_user" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Username: <br>
  <input type="text" name="username"><br>
  Bio: <br>
  <textarea type="text" name="bio"></textarea><br>
  <input type="submit" value="Envoyer le formulaire">
</form>